### ISSUE TITLE
Controlword and statusword are not in Object Dictionary

### ISSUE THREAD

**Issue by bverhagen** [christiansandberg/canopen#238]
While using your library, when executing:

```
node.sdo[0x6040].raw = 0x010F
```

I get the following error:

```
Traceback (most recent call last):
  File "/test_can.py", line 141, in <module>
    main()
  File "/test_can.py", line 51, in main
    reset(node)
  File "/test_can.py", line 11, in reset
    node.sdo[0x6040].raw = 0x010F
  File "/usr/lib/python3.9/site-packages/canopen/variable.py", line 88, in raw
    self.data = self.od.encode_raw(value)
  File "/usr/lib/python3.9/site-packages/canopen/variable.py", line 40, in data
    self.set_data(data)
  File "/usr/lib/python3.9/site-packages/canopen/sdo/base.py", line 112, in set_data
    self.sdo_node.download(self.od.index, self.od.subindex, data, force_segment)
  File "/usr/lib/python3.9/site-packages/canopen/sdo/client.py", line 155, in download
    fp.close()
  File "/usr/lib/python3.9/site-packages/canopen/sdo/client.py", line 381, in write
    response = self.sdo_client.request_response(request)
  File "/usr/lib/python3.9/site-packages/canopen/sdo/client.py", line 85, in request_response
    return self.read_response()
  File "/usr/lib/python3.9/site-packages/canopen/sdo/client.py", line 73, in read_response
    raise SdoAbortedError(abort_code)
canopen.sdo.exceptions.SdoAbortedError: Code 0x06020000, Object does not exist
```

The controlword and statusword are defined in the EDS file I am using with this JVL MIS171 device. On further inspection, `node.sdo` contains many keys, but the code for controlword (0x6040) and statusword (0x6041) are not listed.

Do you have any pointers on how to further debug this or do you know what can cause the controlword nor statusword to be in the SDOs nor in the PDOs?

**Comment by bverhagen** [comment]
Issue was due to an issue in a CANbus slave. Library acted perfectly as it should. Thx!
