### ISSUE TITLE
eds file import error : eds.py line 78 invalid literal for int() with base 0: '001'

### ISSUE THREAD

**Issue by tshh** [christiansandberg/canopen#313]
eds file import error.
even when try to run example codes.
python3.6 3.8 have the same results.
git clone or pip install have the same results.

 >>> import canopen
>>> node = canopen.BaseNode402(35, 'eds/e35.eds')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tshh/canopen/canopen/profiles/p402.py", line 212, in __init__
    super(BaseNode402, self).__init__(node_id, object_dictionary)
  File "/home/tshh/canopen/canopen/node/remote.py", line 37, in __init__
    super(RemoteNode, self).__init__(node_id, object_dictionary)
  File "/home/tshh/canopen/canopen/node/base.py", line 24, in __init__
    object_dictionary = objectdictionary.import_od(
  File "/home/tshh/canopen/canopen/objectdictionary/__init__.py", line 78, in import_od
    return eds.import_eds(source, node_id)
  File "/home/tshh/canopen/canopen/objectdictionary/eds.py", line 78, in import_eds
    t(int(eds.get("DeviceInfo", eprop), 0))
ValueError: invalid literal for int() with base 0: '001'

**Comment by af-silva** [comment]
Hi @tshh,

Thanks for reporting this. The .eds file is a simple example but it had an invalid VendorNumber. I fix this, please check and if you can report back if it is working for you now.

Thanks.
