### ISSUE TITLE
Problems with pdo.read(): Subindex 5 was not found 

### ISSUE THREAD

**Issue by beautifulyautja** [christiansandberg/canopen#327]
Hello, so I am new to canopen and I have encountered some problems when trying to work with PDOs. I have a servo motor which I can control without problems using SDOs. This is my code and the error received:

import canopen
from canopen.profiles.p402 import BaseNode402

node = BaseNode402(1, '/opt/eds_lichuan.eds')

network = canopen.Network()
network.add_node(node)
network.connect(channel='can0', bustype='socketcan', bitrate=500000)
network.check()

node.nmt.state = 'PRE-OPERATIONAL'

node.tpdo.read()

Traceback (most recent call last):
  File "/home/rv/PycharmProjects/try_can_pdo/main.py", line 13, in <module>
    node.tpdo.read()
  File "/home/rv/PycharmProjects/try_can_pdo/venv/lib/python3.9/site-packages/canopen/pdo/base.py", line 56, in read
    pdo_map.read()
  File "/home/rv/PycharmProjects/try_can_pdo/venv/lib/python3.9/site-packages/canopen/pdo/base.py", line 352, in read
    value = self.map_array[subindex].raw
  File "/home/rv/PycharmProjects/try_can_pdo/venv/lib/python3.9/site-packages/canopen/sdo/base.py", line 89, in __getitem__
    return Variable(self.sdo_node, self.od[subindex])
  File "/home/rv/PycharmProjects/try_can_pdo/venv/lib/python3.9/site-packages/canopen/objectdictionary/__init__.py", line 180, in __getitem__
    raise KeyError("Subindex %s was not found" % subindex)
KeyError: 'Subindex 5 was not found'

Process finished with exit code 1

Could you explain the reason this happens? I haven't been able to find an explanation. 
I have read somewhere that subindex 5 is something related to an Event Timer, but I don't understand why I get this error.
Thank you in advance

**Comment by beautifulyautja** [comment]
I have managed to solve the problem. Apparently you need to set up each maximum subindex of the mapping parameters. My driver only has 4, but the default was set to 5. So something like this:

node.sdo[0x1600][0].raw = 4
node.sdo[0x1601][0].raw = 4
node.sdo[0x1602][0].raw = 4
node.sdo[0x1603][0].raw = 4

node.sdo[0x1A00][0].raw = 4
node.sdo[0x1A01][0].raw = 4
node.sdo[0x1A02][0].raw = 4
node.sdo[0x1A03][0].raw = 4
