### ISSUE TITLE
Using "network.scanner.search()" gives an error

### ISSUE THREAD

**Issue by mohse-n** [christiansandberg/canopen#68]
Hello. Thanks for bringing CANOpen to Python.
When I run the following code:
```
#!/usr/bin/env python
import canopen

network = canopen.Network()
network.connect(channel='can0', bustype='socketcan')
network.scanner.search()
network.disconnect()
```

I get the this error:

```
Traceback (most recent call last):
  File "can_scan.py", line 6, in <module>
    network.scanner.search()
  File "/home/quad/.local/lib/python2.7/site-packages/canopen/network.py", line 342, in search
    self.network.send_message(0x600 + node_id, sdo_req)
  File "/home/quad/.local/lib/python2.7/site-packages/canopen/network.py", line 167, in send_message
    self.check()
  File "/home/quad/.local/lib/python2.7/site-packages/canopen/network.py", line 209, in check
    exc = self.notifier.exception
AttributeError: 'Notifier' object has no attribute 'exception'
```

**Comment by mohse-n** [comment]
Upgrading python-can to version 2.1.0 fixed it.
